# -*- coding: utf-8 -*-
"""Question05.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QOBsoA13Lm8087CP8yQTROo768Fpid_z
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt
from google.colab import files


#  Upload images
print("Upload COVER IMAGE (main image)")
uploaded1 = files.upload()

print("Upload SECRET IMAGE (to hide)")
uploaded2 = files.upload()

cover_name = list(uploaded1.keys())[0]
secret_name = list(uploaded2.keys())[0]


img1 = cv2.imread(cover_name)
img2 = cv2.imread(secret_name)

# Resize secret image
img2 = cv2.resize(img2, (img1.shape[1], img1.shape[0]))


# Hide image

hidden = (img1 & 240) | (img2 >> 4)

print("\n===== HIDDEN IMAGE =====")
plt.figure(figsize=(5,5))
plt.imshow(cv2.cvtColor(hidden, cv2.COLOR_BGR2RGB))
plt.title("Hidden Image (Stego Image)")
plt.axis('off')
plt.show()



choice = input("\nDo you want to extract the original secret image? (yes/no): ")

if choice.lower() == "yes":

    extracted = (hidden & 15) << 4

    print("\n===== EXTRACTED IMAGE =====")
    plt.figure(figsize=(5,5))
    plt.imshow(cv2.cvtColor(extracted, cv2.COLOR_BGR2RGB))
    plt.title("Extracted Secret Image")
    plt.axis('off')
    plt.show()

else:
    print("Extraction skipped.")